---
kind: pipeline
type: kubernetes
name: latest

node_selector:
  kubernetes.io/arch: amd64

steps:
- name: build
  commands:
  - make latexmk/index.pdf
  image: docker.io/volkerraschek/latex:latest-archlinux
  resources:
    requests:
      cpu: 250
      memory: 500M
    limits:
      cpu: 500
      memory: 750M

- name: push-fhtrier
  depends_on:
  - build
  image: docker.io/appleboy/drone-scp:1.6.2
  settings:
    host: ssh.hochschule-trier.de
    user:
      from_secret: ssh_user_fh-trier
    key:
      from_secret: ssh_key
    port: 22
    command_timeout: 2m
    target:
    - /dozenten/peschm/tgdb_ws1819
    source:
    - index.pdf
    - sql/schema_01.sql
    - sql/sqlplus-settings.sql
  when:
    branch:
    - master
    repo:
    - fh-trier/tgdb_ws1819
    event:
    - push
    - cron

- name: push-nextcloud
  commands:
  - curl --fail --user $WEBDAV_USER:$WEBDAV_PASSWORD --upload-file index.pdf --location https://nextcloud.cryptic.systems/remote.php/dav/files/$WEBDAV_USER/Dokumente/Studium/Fachschaftdaten/DB_1_-_Grundlagen_Datenbanken/Tutorien/Tutorium_WS1819/Tutorium_WS1819.pdf
  - curl --fail --user $WEBDAV_USER:$WEBDAV_PASSWORD --upload-file sql/schema_01.sql --location https://nextcloud.cryptic.systems/remote.php/dav/files/$WEBDAV_USER/Dokumente/Studium/Fachschaftdaten/DB_1_-_Grundlagen_Datenbanken/Tutorien/Tutorium_WS1819/schema.sql
  - curl --fail --user $WEBDAV_USER:$WEBDAV_PASSWORD --upload-file sql/sqlplus-settings.sql --location https://nextcloud.cryptic.systems/remote.php/dav/files/$WEBDAV_USER/Dokumente/Studium/Fachschaftdaten/DB_1_-_Grundlagen_Datenbanken/Tutorien/Tutorium_WS1819/sqlplus-settings.sql
  depends_on:
  - build
  environment:
    WEBDAV_USER:
      from_secret: webdav_username
    WEBDAV_PASSWORD:
      from_secret: webdav_password
  image: docker.io/volkerraschek/latex:latest-archlinux
  resources:
    limits:
      cpu: 150
      memory: 150M
  when:
    repo:
    - fh-trier/tgdb_ws1819
    event:
    - push
    - cron

- name: email-notification
  depends_on:
  - push-fhtrier
  - push-nextcloud
  environment:
    PLUGIN_HOST:
      from_secret: smtp_host
    PLUGIN_USERNAME:
      from_secret: smtp_username
    PLUGIN_PASSWORD:
      from_secret: smtp_password
    PLUGIN_FROM:
      from_secret: smtp_mail_address
  image: docker.io/drillster/drone-email:latest
  resources:
    limits:
      cpu: 150
      memory: 150M
  when:
    status:
    - changed
    - failure

trigger:
  event:
    exclude:
    - tag

---
kind: pipeline
type: kubernetes
name: release

node_selector:
  kubernetes.io/arch: amd64

steps:
- name: build
  commands:
  - make latexmk/index.pdf
  environment:
    VERSION: ${DRONE_TAG}
  image: docker.io/volkerraschek/latex:latest-archlinux
  resources:
    requests:
      cpu: 250
      memory: 500M
    limits:
      cpu: 500
      memory: 750M

- name: push-nextcloud
  commands:
  - curl --fail --user $WEBDAV_USER:$WEBDAV_PASSWORD --upload-file index.pdf --location https://nextcloud.cryptic.systems/remote.php/dav/files/$WEBDAV_USER/Dokumente/Studium/Fachschaftdaten/DB_1_-_Grundlagen_Datenbanken/Tutorien/Tutorium_WS1819/Tutorium_WS1819_${DRONE_TAG}.pdf
  - curl --fail --user $WEBDAV_USER:$WEBDAV_PASSWORD --upload-file sql/schema_01.sql --location https://nextcloud.cryptic.systems/remote.php/dav/files/$WEBDAV_USER/Dokumente/Studium/Fachschaftdaten/DB_1_-_Grundlagen_Datenbanken/Tutorien/Tutorium_WS1819/schema_${DRONE_TAG}.sql
  - curl --fail --user $WEBDAV_USER:$WEBDAV_PASSWORD --upload-file sql/sqlplus-settings.sql --location https://nextcloud.cryptic.systems/remote.php/dav/files/$WEBDAV_USER/Dokumente/Studium/Fachschaftdaten/DB_1_-_Grundlagen_Datenbanken/Tutorien/Tutorium_WS1819/sqlplus-settings_${DRONE_TAG}.sql
  environment:
    WEBDAV_USER:
      from_secret: webdav_username
    WEBDAV_PASSWORD:
      from_secret: webdav_password
  image: docker.io/volkerraschek/latex:latest-archlinux
  resources:
    limits:
      cpu: 150
      memory: 150M

- name: push-gitea
  image: docker.io/plugins/gitea-release:latest
  resources:
    limits:
      cpu: 150
      memory: 150M
  settings:
    base_url: https://git.cryptic.systems
    api_key:
      from_secret: gitea_token
    files:
    - index.pdf
    checksum:
    - md5
    - sha1
    - sha256
    - sha512
    - adler32
    - crc32

- name: email-notification
  environment:
    PLUGIN_HOST:
      from_secret: smtp_host
    PLUGIN_USERNAME:
      from_secret: smtp_username
    PLUGIN_PASSWORD:
      from_secret: smtp_password
    PLUGIN_FROM:
      from_secret: smtp_mail_address
  image: docker.io/drillster/drone-email:latest
  resources:
    limits:
      cpu: 150
      memory: 150M
  when:
    status:
    - changed
    - failure

trigger:
  event:
  - tag
  repo:
  - fh-trier/tgdb_ws1819

---
kind: pipeline
type: kubernetes
name: sync

node_selector:
  kubernetes.io/arch: amd64

steps:
- name: github
  image: docker.io/appleboy/drone-git-push:latest
  resources:
    limits:
      cpu: 150
      memory: 150M
  settings:
    branch: master
    remote: ssh://git@github.com/fh-trier/tgdb_ws1819.git
    force: true
    ssh_key:
      from_secret: ssh_key

- name: email-notification
  environment:
    PLUGIN_HOST:
      from_secret: smtp_host
    PLUGIN_USERNAME:
      from_secret: smtp_username
    PLUGIN_PASSWORD:
      from_secret: smtp_password
    PLUGIN_FROM:
      from_secret: smtp_mail_address
  image: docker.io/drillster/drone-email:latest
  resources:
    limits:
      cpu: 150
      memory: 150M
  when:
    status:
    - changed
    - failure

trigger:
  event:
  - push
  repo:
  - fh-trier/tgdb_ws1819
