version: "2"
services:
  oracle:
    container_name: oracle-db
    image: sath89/oracle-12c
    ports:
      - 8080:8080
      - 1521:1521
    volumes:
      - /srv/docker/oracle-db/data:/u01/app/oracle
